### ISSUE TITLE
[Video / Feedback]: Refunds?

### ISSUE THREAD

**Issue by maxms** [archetyped/simple-lightbox-extensions#104]
Hello, I want to try your video extension for use in an Elementor loop template. If it doesn't work for us, do you offer refunds?

**Comment by archetyped** [comment]
Hi, refunds may be issued on a case-by-case basis.  The video extension works wherever SLB does, so testing to confirm image links are properly opened in the lightbox in your Elementor loop template is recommended.

If you run into an issue with SLB itself, please feel free to [create a support ticket](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support) and I would be glad to take a look.
