### ISSUE TITLE
[Video] Not playing on Wordpress site (Stockholm theme)

### ISSUE THREAD

**Issue by paolinidesign** [archetyped/simple-lightbox-extensions#105]
## Description of Problem

Even with the lightbox video plugin, the video does not work, when I click on it, the overlay appears, it spins for a few seconds but the video doesn’t show.

## Details

* URL of Page exhibiting problem: https://paolinidesign.com/paolinidesign/portfolio_page/cappellini-web-design/ (click on the video to reproduce)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome and Safari, did not test others
* Version of SLB Installed: Version 2.8.1 
* Other plugins installed: Simple Lightbox: Video Handler Version 0.2.1

**Comment by archetyped** [comment]
Hi, SLB does not appear to be activated at the link provided.  Please provide an updated link with SLB activated that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
