### ISSUE TITLE
[Video / Request]: リンク切れの対応

### ISSUE THREAD

**Issue by NEET-MAN25** [archetyped/simple-lightbox-extensions#111]
## Description of feature/request

リンク切れに対応する機能があると便利だと思います。（「この動画は現在表示できません」などの表示をして自動で終了するなど）

## This feature would be used to

（参考URL）https://murakumo25.com/vibram-arctic-grip/49021

リンク先の動画がすでに存在していない場合（リンク切れ）、ぐるぐるとロード画面が続くだけ、というのは快適ではありません。

_※リンク切れを把握している場合、実際にはこちらで対応したほうがウェブサイトとして効果的なのですが、全てを把握して快適にするのは難しいのです。_

![bandicam 2022-12-24 13-40-58-531](https://user-images.githubusercontent.com/120386224/209421858-c572c43d-4507-4b99-a451-8307a7f3e985.jpg)

**Comment by archetyped** [comment]
Hi, handling broken links would be more of a functionality of the core SLB plugin, so I've moved it to SLB's feature requests forum for further discussion:

[Idea: Handling Broken Links](https://github.com/archetyped/simple-lightbox/discussions/988)

Thanks.
