### ISSUE TITLE
[WooCommerce/Support]: 

### ISSUE THREAD

**Issue by HansjuergJ** [archetyped/simple-lightbox-extensions#112]
Lightbox with Woocommerce extension does nothing.
I have a Themeforest / Ashade-Photography Theme .
I would like to display the individual images large in the albums.

Best regards
Hansjürg Jenzer

* URL of Page exhibiting problem: https://hansjuergjenzer.ch/albums/classic-tat/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: ??
* Other plugins installed: 
![Plugin 1](https://user-images.githubusercontent.com/124173691/216080804-3e814b7d-e7b5-4c13-804c-939e3a7e501f.jpg)
![Plugin 2](https://user-images.githubusercontent.com/124173691/216080848-0b221b55-4233-47b6-b835-503dcb569375.jpg)

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the URL you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.  If you are using a third-party gallery from a theme or plugin, please refer to that gallery's documentation for adding links to the images.

If you are still experiencing an issue after adding links to the images, please provide the following details and I would be glad to reopen this ticket and take another look:

* Updated URL of page exhibiting issue.
* Version of Simple Lightbox (SLB) installed.
* Version of WooCommerce installed.

Thank you.
