### ISSUE TITLE
[Video / Issue]: Link opened in Youtube, not in a lightbox

### ISSUE THREAD

**Issue by AELLIOWA** [archetyped/simple-lightbox-extensions#118]
## Description of issue
https://jazzinmacao.com/concerts-2025/
PAssword : 1234
I have installed the 2 plugin SImple Lighbox and its video tension only to the website jazzinmacao.com
I tried to create a link to a video. from the picture to illustrate ELECTRO SWING CONCERT 
It is opened normally, not in a LightBox.
I kept the default plugin setup as it.

## Details

* URL of page exhibiting the issue: https://jazzinmacao.com/concerts-2025/ 
* Password : 1234
* Web Browser(s) that exhibit the issue: chrome
* Simple Lightbox Version: 2.9.3
* Active theme: Elegant Theme
* Other plugins installed: 
Admin Menu Post/Page Counter
Admin Menu Tree Page View	
All in one Favicon
Broken Link Checker
Disable Lazy Load
Elegant Themes Updater
Enable SVG, WebP, and ICO Upload	
EWWW Image Optimizer
Login Designer
Multisite Plugin Stats
Page Links To
Page Menu Editor	
WordPress MU Domain Mapping
WP File Manager
WP Force SSL
WP-Optimize - Clean, Compress, Cache
XML Sitemap Generator for Google

**Comment by AELLIOWA** [comment]
corresponding source code on the page : 
```html
<a href="https://youtu.be/9TQBz2vJw00?si=zkrn1bmeFhJtzSff" data-slb-active="1" data-slb-asset="1603446573" data-slb-group="139"><span class="et_pb_image_wrap et_pb_only_image_mode_wrap"><img decoding="async" width="1080" height="720" src="http://jazzinmacao.com/wp-content/uploads/sites/16/2023/10/parov-stelar-jazz-in-macao.jpg" alt="" srcset="https://jazzinmacao.com/wp-content/uploads/sites/16/2023/10/parov-stelar-jazz-in-macao.jpg 1080w, https://jazzinmacao.com/wp-content/uploads/sites/16/2023/10/parov-stelar-jazz-in-macao-980x653.jpg 980w, https://jazzinmacao.com/wp-content/uploads/sites/16/2023/10/parov-stelar-jazz-in-macao-480x320.jpg 480w" sizes="(min-width: 0px) and (max-width: 480px) 480px, (min-width: 481px) and (max-width: 980px) 980px, (min-width: 981px) 1080px, 100vw" class="et-waypoint et_pb_animation_off et_pb_animation_off_tablet et_pb_animation_off_phone wp-image-314 et-animated"></span></a>
```

**Comment by archetyped** [comment]
Hi, it appears that the `<div>` element containing the thumbnail link has a click event handler that is intercepting the clicks and stopping SLB from running.

Removing/disabling whatever is allowing the `<div>` elements to be clickable should allow the thumbnail link to be properly clicked and display the video in the lightbox.

Please provide an updated link if you are still experiencing an issue once the click `<div>` click event handler has been removed and I would be glad to take another look.
