### ISSUE TITLE
[Video / Issue]: No lightbox

### ISSUE THREAD

**Issue by AureliosPiro** [archetyped/simple-lightbox-extensions#121]
## Description of issue

I have installed the plugin and activated it from on my WordPress. However, nothing has changed. As you can see my website doesn't have a lightbox yet. What did I do wrong?

Does it work only with the Gutenberg editor or does it work with the Elementor editor as well?

## Details

* URL of page exhibiting the issue: 
https://nacaoia.com.br/usando-a-pictory-ai/

* Web Browser(s) that exhibit the issue: 
Chrome and Edge

* Simple Lightbox Version: 
The lastest. I just bought the plugin 1 hour ago.

* Active theme: 
Newsup

* Other plugins installed: 
Elementor free, Matomo analytics, duplicate page, Rank math,

**Comment by archetyped** [comment]
Hi, there do not appear to be any video links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

Solution: Add supported video links (e.g. to a YouTube video) and SLB's Video Extension will display them in the lightbox when clicked.

If you are still experiencing an issue after adding video links, please provide the following and I would be glad to reopen this ticket and take another look:

* Version of SLB installed (note: "lastest" is not a valid version.  All plugin versions are listed on your site's Plugins admin page).
* Version of Video Extension installed.
* Screenshot of SLB's settings page.
* Screenshot of Site's active plugins page.
* URL of page that exhibits the issue you are experiencing.

Thanks.
