### ISSUE TITLE
Simple Lightbox: WooCommerce Activator doesn't activate

### ISSUE THREAD

**Issue by Markmcl** [archetyped/simple-lightbox-extensions#53]
I have deactivated all plugins except lightbox and woocommerce, and tested with default woocommerce 'storefront' theme, with cache cleared with each test. Site is new and just loaded with dummy data. SLB does work on blog post. Just won't work on woocommerce items.
Simple Lightbox: WooCommerce Activator: V 0.2.1
Simple Lightbox: V2.6.0
https://amazingmomentscq.com.au/shop/music/woo-album-2/
tested in firefox, chrome, edge
plugin details etc:
// Generated by the RS System Diagnostic Plugin //

//// Browser of Current Viewer ///////////////////

     Platform:            Windows 
     Browser Name:        Firefox 
     Browser Version:     50.0 
     User Agent String:   Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0 

//// End Browser of Current Viewer ///////////////

Website Name:             Amazing Moments CQ

WordPress Address (URL):  https://amazingmomentscq.com.au/amazing  |  site_url() - The location where your WordPress core files reside.
Site Address (URL):       https://amazingmomentscq.com.au  |  home_url() - The URL people should use to get to your site.

WordPress Version:        4.6.1
Multisite:                No
Permalink Structure:      /%category%/%postname%/
Active Theme:             Amazing Storefront 1.0.0

Web Host:                 SiteGround

PHP Version:              5.6.28
MySQL Version:            5.6.28-76.1-log
Server Software:          Apache / Linux
Server Hostname:          sgp18.siteground.asia

WP Memory Limit:          40M  |  WARNING - PERFORMANCE: WordPress Memory Limit too low. Should be at least 64MB. 96-128MB+ is recommended.
WP Admin Memory Limit:    768M
Current WP Memory Used:   76.64M
Max WP Memory Used:       76.64M
PHP Safe Mode:            No
PHP Memory Limit:         768M
PHP Upload Max Size:      128M
PHP Post Max Size:        128M
PHP Upload Max Filesize:  128M
PHP Time Limit:           120
PHP Max Input Vars:       3000
PHP Arg Separator:        &
PHP Allow URL File Open:  Yes
PHP Short Open Tags:      Enabled  |  WARNING - SECURITY: 'short_open_tag' should be disabled.
Expose PHP:               No

WP_DEBUG:                 Disabled
WP_DEBUG_LOG:             Disabled
WP_DEBUG_DISPLAY:         Enabled
SCRIPT_DEBUG:             Disabled
WP_CACHE:                 Disabled
AUTOSAVE_INTERVAL:        60
WP_POST_REVISIONS:        1
EMPTY_TRASH_DAYS:         30
DISALLOW_FILE_EDIT:       Enabled

WP Database Size:         3.84M
WP Table Prefix Length:   9  |  STATUS: ACCEPTABLE
WP Table Prefix Default:  No

Show On Front:            page
Page On Front:            Welcome (#4)
Page For Posts:           Blog (#6)
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed

WP Remote Post:           wp_remote_post() works

PHP Sessions:             Active
Default Session Name:     PHPSESSID  |  WARNING - SECURITY: 'session.name' should be set to a custom value, not the PHP default.
Session Cookie Path:      /
Session Save Path:        /tmp
Use Session Cookies:      On
Session Use Cookies Only: Off  |  WARNING - SECURITY: 'session.use_only_cookies' should be enabled.
Session Cookie HTTP Only: Off  |  WARNING - SECURITY: 'session.cookie_httponly' should be enabled to prevent JavaScript from accessing Session Cookies.

DISPLAY ERRORS:           N/A
ERROR LOGGING:            On
ERROR LOG LOCATION:       php_errorlog
ERROR REPORTING LEVEL:    E_RECOVERABLE_ERROR | E_USER_WARNING | E_USER_ERROR | E_COMPILE_ERROR | E_CORE_WARNING | E_CORE_ERROR | E_PARSE | E_WARNING | E_ERROR

FSOCKOPEN:                Your server supports fsockopen.
cURL:                     Your server supports cURL.
SOAP Client:              Your server has the SOAP Client enabled.
SUHOSIN:                  Your server does not have SUHOSIN installed.
MySQLi:                   Your server has the MySQLi extension enabled.

ACTIVE PLUGINS:

AntiVirus: 1.3.9
BackupBuddy: 7.1.6.2
BNE Gallery Extended: 1.0.3
BNE Testimonials: 1.7.5
Breadcrumb Trail: 1.0.0
Cart to Quote for Woocommerce: 1.0.5
Envato Market: 1.0.0-RC2
Gmail SMTP: 1.0.6
Google Apps Login: 2.10.4
HTML Editor Syntax Highlighter: 1.7.2
Jetpack by WordPress.com: 4.4
Login Logo: 0.7
Manual Control for Jetpack: 0.2
Menu Humility: 0.3
Meteor Slides: 1.5.6
Remove Widget Titles: 1.0
Reveal IDs: 1.4.6.2
RS System Diagnostic: 1.0.2
Shield: 5.5.4
Show Current Template: 0.3.0
Sidebar Login: 2.7.3
Simple Catalog for WooCommerce: 1.1
Simple Lightbox: 2.6.0
Simple Lightbox: WooCommerce Activator: 0.2.1
Storefront Footer Bar: 1.0.3
Sucuri Security - Auditing, Malware Scanner and Hardening: 1.8.3
TinyMCE Advanced: 4.4.1
UpdraftPlus - Backup/Restore: 1.12.28
WooCommerce: 2.6.8
WordPress Importer: 0.6.3
WP-SpamShield: 1.9.9.6
WP Mail Logging: 1.7.0
WP Max Submit Protect: 1.1.2

TOTAL ACTIVE PLUGINS: 33  |  WARNING - PERFORMANCE: Using this many plugins can cause site slowdowns and conflicts. Try to minimize plugins used.

INACTIVE PLUGINS:

All In One SEO Pack: 2.3.11
Autoptimize: 2.1.0
WP Super Cache: 1.4.8

TOTAL INACTIVE PLUGINS: 3

**Comment by Markmcl** [comment]
I now have it working,have to enable lightbox in wooc settings -- duh. but I didn't think it would apply to SLB as well. However it is not pulling the short description into the lightbox. Am I missing something else obvious?
Also, when using default woo lightbox, thumbnails are scaled to fit as in attached image, but do not scale when using SLB. Is this possible with SLB
![default wooc lightbox thumbs scaled](https://cloud.githubusercontent.com/assets/6374448/20587595/9f777ccc-b25a-11e6-8149-c9601f5607ed.JPG)
 without changing thumb size in settings which could be inconvenient elsewhere 
![slb settings](https://cloud.githubusercontent.com/assets/6374448/20587396/0b6419a6-b259-11e6-8772-9a7528439be1.JPG)

**Comment by Markmcl** [comment]
Without Simple Lightbox: WooCommerce Activator activated (wooc prettyphoto working) there is a class of  "zoom" as well as "first" applied to the "a" tag.   "zoom" has the following css applied

`.single-product div.product .images .thumbnails a.zoom {
    float: left;
    margin-right: 14.2857%;
    width: 14.2857%;
}
.single-product div.product .images .thumbnails a.zoom {
    display: block;
    float: left;
    margin-bottom: 1em;
    margin-right: 3.8%;
    width: 22.05%;
}`
which enables the layout and styling of the thumbnails.

**Comment by archetyped** [comment]
Hi, apologies for the delayed response.  I'm glad you were able to get the lightbox working.  SLB basically acts as a drop-in replacement for WooCommerce's default lightbox, so it also respects WooCommerce's lightbox setting.  For future reference, this is noted in the **Installation** section of the add-on's `readme.txt` file:

> When the lightbox is enabled in WooCommerce's settings, Simple Lightbox will display images in a lightbox.

The "Activate WooCommerce Short Description" option allows links added to a product's short description to be displayed in the lightbox when clicked.  If you are experiencing different behavior than this, please provide a link to a product page with links in the short description and I will take a look.

SLB should not be affecting the layout on the page (it only controls the lightbox), but I will take a look to see if WooCommerce's default lightbox was adding CSS classes to links on the page that affected their layout.  I will post an update when I have additional information.

Thanks.

**Comment by Markmcl** [comment]
Ah! 
Ithought The "Activate WooCommerce Short Description"  option meant the "Short description" itself would display in the lightbox.

WooCommerce or WooCommerce's default lightbox is definitely adding tha class of "zoom" as far as I can tell, as outlined above.
Attached is screenprint of https://amazingmomentscq.com.au/shop/woo-album-2/ with SLB enabled.
![slb enabled](https://cloud.githubusercontent.com/assets/6374448/20777127/ad08e8c0-b7b0-11e6-8604-ef2cda27f5b5.JPG)

Is there further info you require from me?

**Comment by Markmcl** [comment]
I must have clicked the wrong button. Didn't mean to close this.
I added this to style.css of child theme and it gives a good layout. It is actually better as 150 by 150 thumbnail are better than really scaled small ones set by woo
`.size-shop_thumbnail {
    display: inline-block;
    margin: 0 10px 10px 0;
}`

**Comment by Markmcl** [comment]
example page is now at https://amazingmomentscq.com.au/product/woo-album-2/

**Comment by archetyped** [comment]
Closing old ticket as there have been updates to SLB's WooCommerce Extension.  If you are experiencing an issue after updating to the latest version of the extension, please [create a new ticket](https://github.com/archetyped/simple-lightbox-extensions/issues/new/choose).
