### ISSUE TITLE
[WooCommerce / Issue]: Error: Missing Argument (2)

### ISSUE THREAD

**Issue by Markmcl** [archetyped/simple-lightbox-extensions#60]
## Description of issue

Hello
since the latest update to Woocommerce I get the following warning

Warning: Missing argument 3 for SLB_WooCommerce::activate_product_thumbnail(), called in /home/username/public_html/amazing/wp-includes/class-wp-hook.php on line 298 and defined in /home/username/public_html/amazing/wp-content/plugins/slb-woocommerce_0.2.1/controller.php on line 107

Woo has changed how it handles images so suppose this is the problem

## Details

* URL of page exhibiting the issue: 
* Web Browser(s) that exhibit the issue:
* WooCommerce version:  
* Simple Lightbox version: 
* SLB WooCommerce add-on version: 
* Active theme/version:
* Other plugins installed:

**Comment by Markmcl** [comment]
more details
everything is completely up to date
I should have looked, but it appears 'smooty1970'  is having the same or very similar issue. I am using a child theme of Woo's Storefront theme, & have done the usual tests to try and isolate the problem. The site isn't public yet, but could make available and email link if necessary

**Comment by archetyped** [comment]
Hi, please fill in the details of your issue and I would be glad to take a look.  Versions can change frequently, so noting the specific version you are using is very important.

Thanks.

**Comment by Markmcl** [comment]
I left this for a few days to see if anticipated updates to Woocommerce changed anything however no luck. 
Here is a page exhibiting the problem:
https://amazingmomentscq.com.au/product/woo-album-1/
I have tested in Firefox, Chrome,& Edge
WooCommerce version is 3.0.3. There has only been a problem since WC v 3
SLB   v 2.6
SLB: WC Activator  v 0.2.1
theme is a child of Woo Commerce Storefront

Other plugins
All In One SEO Pack  not activated 
AntiVirus
Autoptimize   not activated
BackupBuddy
BNE Gallery Extended
BNE Testimonials
Breadcrumb Trail
Cart to Quote for Woocommerce
Envato Market
Gmail SMTP
Google Apps Login
HTML Editor Syntax Highlighter
Jetpack 
Login Logo
Manual Control for Jetpack 
Menu Humility
Meteor Slides
Monomeath WooCommerce shop display
Remove Widget Titles
Reveal IDs
Shield
Show Current Template
Sidebar Login
Simple Catalog for WooCommerce
Simple Lightbox
Simple Lightbox: WooCommerce Activator
Storefront Footer Bar
Sucuri Security
TinyMCE Advanced
UpdraftPlus  not activated
WooCommerce 
WP Super Cache   not activated

**Comment by archetyped** [comment]
Thank you, I have updated your original post with the details you have provided.

I have confirmed your issue.  Changes to major version numbers generally mean there are potentially breaking changes, so I am currently evaluating the changes to WooCommerce to see what needs to be done to make the add-on compatible with the new version.

Thanks.

**Comment by Markmcl** [comment]
Hello
I was wondering if you have an update for this?
thanks

**Comment by mattgipson** [comment]
I just bought the plugin and I am getting the same issue out of the gate. Any update or fix suggestion for this @archetyped ?

**Comment by archetyped** [comment]
Hi @Markmcl, WooCommerce has completely changed its image implementation in v3+, so development on supporting v3+ is currently underway.

@mattgipson are you using WooCommerce v3+ or an earlier version?  As noted on the [add-on's page](https://archetyped.com/lab/slb-woocommerce-beta/), support for WooCommerce v3+ is coming soon.  If you are using an earlier version, please [create a new ticket for your issue](https://github.com/archetyped/slb-addons/wiki/Reporting-Issues) and I would be glad to take a look.

Thanks.

**Comment by OnnoGeorg** [comment]
Hi, any update on this? Is WooCommerce v3+ supported now?

**Comment by archetyped** [comment]
[SLB's WooCommerce Extension](https://archetyped.com/lab/slb-woocommerce-beta/) now supports WooCommerce v3+ (including v4+).
