### ISSUE TITLE
[WooCommerce / Issue]: This plugin breaks the product page

### ISSUE THREAD

**Issue by rvanate** [archetyped/simple-lightbox-extensions#74]
Woocommerce version 3.5.7 using Simple Lightbox: WooCommerce Activator version 0.2.1. php 7.2.14

Single product page does not show anything when plugin is active.

**Comment by archetyped** [comment]
Hi, can you please clarify which add on you are experiencing problems with? Your title refers to the video add-on, while your post mentions the WooCommerce add-on.

Thanks.

**Comment by rvanate** [comment]
Sorry, it is the WooCommerce add-on. (Simple Lightbox: WooCommerce Activator)

**Comment by archetyped** [comment]
Thank you for the clarification.

The WooCommerce add-on has been tested with WooCommerce 3.5.7, and no conflicts were found.  Please clear all caches (browser, caching plugins. etc.) when making changes to your site (updating WordPress, changing/updating themes or plugins, etc.), as stale cached data can cause unexpected behavior.

Also note that the WooCommerce add-on currently supports up to WooCommerce v2.6.14 ([more information on the add-on's page](https://archetyped.com/lab/slb-woocommerce-beta/)), but later versions of WooCommerce should continue to function normally when the add-on is activated.

If you are still experiencing this issue, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
