### ISSUE TITLE
[WooCommerce / Issue]: How to use 

### ISSUE THREAD

**Issue by rajatshanbhag** [archetyped/simple-lightbox-extensions#79]
## Description of Problem

I just paid for the Woocommerce add on feature and still not able to figure out how it works. 
from what I understood from the instruction was, I would be able to add description/cart option for each image from my gallery page (for those images which are listed as products in my Woocommerce). Help :)

Rajat

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, the add-on allows WooCommerce product image links to be displayed in SLB's lightbox (just like image links on standard posts/pages).

Once you've confirmed your site meets the requirements listed in the **Requirements** section of the [WooCommerce add-on's page](https://archetyped.com/lab/slb-woocommerce-beta/), please update your original post to include the necessary details to fully evaluate your issue:

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
