### ISSUE TITLE
[Support]: Lightbox Not Working

### ISSUE THREAD

**Issue by SynergyCraft** [archetyped/simple-lightbox-extensions#82]
I did a google search and got a few returns for "lightbox on hover". The plugin is not doing what I was hoping it would. I will find another alternative. Please issue Refund. 

I will continue my case with PayPal until this is resolved.

## Description of Problem

The lighbox plugin is not working with Woocommerce Products

I purchased the add on to have lightboxes on Woocommerce products, specifically on https://synergycraftstudio.com/decal-catalog/ 

Please issue refund if not workable. I will contact PayPal tomorrow if I don't hear backk.

Thank you

## Details

* URL of Page exhibiting problem: https://synergycraftstudio.com/decal-catalog/ 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 
* Version of WooCommerce Installed: 
* Version of SLB WooCommerce Extension Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB and the WooCommerce extension appear to be working on WooCommerce product pages on your site:

Example: https://synergycraftstudio.com/product/mermaid-pillow-unicorn/

If you are experiencing something different, please update your original post to include the requested details so that your issue can be fully evaluated.  Please also provide a link to a specific page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
> 📒 Transferred @SynergyCraft's comments from duplicate ticket #83 

SLB is not working as you've shown in Chrome or Firefox. I've attached a screenshot of what I see in Firefox which represents the same view as seen in Chrome. Also, the lightbox is not behaving as expected on "Our Designs" page which is also filled with WooCommerce products filtered through Strorefront Blocks.

## Details

* URL of Page exhibiting problem: https://synergycraftstudio.com/decal-catalog/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox and Chrome
* Version of SLB Installed: Simple Lightbox WooCommerce Extension

![Simple Light Box Not Working (on hover either)](https://user-images.githubusercontent.com/67302938/85743740-ec751800-b6c9-11ea-85e7-adf07ae67da1.jpg)

**Comment by archetyped** [comment]
Hi, just for clarification, are you saying that SLB is not working when the product gallery image is clicked at the link I provided above (https://synergycraftstudio.com/product/mermaid-pillow-unicorn/)?

If so, then you may have an issue with your browser, as that page works when tested on multiple devices and browsers.  Clearing your browser's cache and fully refreshing the page is recommended before testing in case your browser is loading an outdated version of the page.

The link you provided (https://synergycraftstudio.com/decal-catalog/) only contains links to product pages, not images.  As per SLB's **Usage** section on [WordPress' Plugin Directory](https://wordpress.org/plugins/simple-lightbox/), SLB works with **links to images**.

Also, lightboxes (SLB included) generally require a link to be clicked for the lightbox to be displayed.  Hovering over a link to display a lightbox is not supported by SLB, nor by any other lightbox plugin as far as I am aware.

Finally, the product page in the screenshot you provided uses an SVG vector file.  SLB supports standard bitmap images (JPEG, PNG, GIF, etc.).  Standard bitmap images (as used on https://synergycraftstudio.com/product/mermaid-pillow-unicorn/) will be displayed in SLB's lightbox when clicked.

If you are experiencing an issue beyond what is noted above, please edit your original post above (click the 3 dots in top-right corner of the post and select "Edit") and provide the details as previously-requested (SLB version, WooCommerce version, etc.), as that information is necessary to reproduce your issue.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
