### ISSUE TITLE
[Support]: Same Issue SLB Not Working as Expected

### ISSUE THREAD

**Issue by SynergyCraft** [archetyped/simple-lightbox-extensions#83]
## Description of Problem

SLB is not working as you've shown in Chrome or Firefox. I've attached a screenshot of what I see in Firefox which represents the same view as seen in Chrome. Also, the lightbox is not behaving as expected on "Our Designs" page which is also filled with WooCommerce products filtered through Strorefront Blocks.

## Details

* URL of Page exhibiting problem: https://synergycraftstudio.com/decal-catalog/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox and Chrome
* Version of SLB Installed: Simple Lightbox WooCommerce Extension

![Simple Light Box Not Working (on hover either)](https://user-images.githubusercontent.com/67302938/85743740-ec751800-b6c9-11ea-85e7-adf07ae67da1.jpg)

**Comment by archetyped** [comment]
Hello, please do not create duplicate tickets.  I have copied your above comments over to [your existing ticket](82).  Please refer to that ticket to keep all discussion in one place.
