### ISSUE TITLE
Links/Buttons Appearance

### ISSUE THREAD

**Issue by seiichi77** [archetyped/simple-lightbox-extensions#86]
## Description of Problem

I want all the lightbox buttons to be the same size. no matter the length of the word in the button. 

## Details

I'm using Elementor as my editor
![buttons](https://user-images.githubusercontent.com/8428706/98011654-5fe41000-1db5-11eb-9403-e25d8214a24f.png)

* URL of page exhibiting the issue: 
* Web Browser(s) that exhibit the issue: 
* Simple Lightbox Version: 
* Active theme: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB does not have any affect over the appearance of buttons or links on the page.  SLB only controls the appearance of the lightbox itself that is displayed when a link is clicked.

Contacting the developers of the button/link appearance (page builder plugins, theme, etc.) is recommended.
