### ISSUE TITLE
Video/Issue: Lightbox not working

### ISSUE THREAD

**Issue by xegos** [archetyped/simple-lightbox-extensions#88]
Link to video lightbox just shows the spinner. YouTube video is not showing up.

## Details

* URL of Page exhibiting problem: https://accumark.us/services/
* Firefox 84.0.1 (64-bit)
* SLB Version 2.8.1 with Simple Lightbox: Video Handler Version 0.2.0
* Other plugins installed: Yoast SEO, WP Sitemap Page, Widget Logic, Themify Updater, Themify Shortcodes, Themify Builder Pro, Slider Revolution, Scroll Back to Top, Responsive Menu, Redirection, Really Simple SSL, Duplicate Page, Contact Form DB, Contact Form 7, Better Search Replace, All In One WP Security, Advanced iFrame

**Comment by archetyped** [comment]
Thanks for the report. YouTube appears to have recently changed how videos are retrieved.

This has been fixed and an update will be released soon (notification will be sent to email used to purchase extension).
