### ISSUE TITLE
[Video / Request]: MP4 support

### ISSUE THREAD

**Issue by bitkahuna** [archetyped/simple-lightbox-extensions#91]
## Description of feature/request

i'd like to get this but i need to be able to play an mp4 file.

## This feature would be used to

play an mp4 not on youtube or vimeo. could be on website host or on amazon s3 with public url.

**Comment by archetyped** [comment]
Duplicate of #7

Please check for existing posts before creating a new one to keep all discussion in one place.  Add your vote/comments to the existing post as development is prioritized by demand.

Thanks.
