### ISSUE TITLE
[Video / Request]: add support for youtube-nocookie (aka privacy enhanced mode)

### ISSUE THREAD

**Issue by donbowman** [archetyped/simple-lightbox-extensions#93]
## Description of feature/request

the tldr: using www.youtube-nocookie.com instead of www.youtube.com results in being able to embed w/o having cookies dropped on the user (until they take an action).

https://support.google.com/youtube/answer/171780?hl=en

in this plugin, the match looks like:
`'#^https?://((www\.)?youtube.com/watch.*|youtu.be/.+)#'`

i think it should have (?maybe?) `'#^https?:\/\/((www\.)?youtube(-nocookie)?.com\/watch.*|youtu.be\/.+)#'`

**Comment by archetyped** [comment]
Hi, SLB displays content from links on the page, while the `youtube-nocookie.com` domain is only for embedding videos on a page.  That domain does not support links.

As such, modifying the link URL matching expression would not apply here.
