### ISSUE TITLE
[Video / Feedback]: Need update notification within WordPress

### ISSUE THREAD

**Issue by purplearth** [archetyped/simple-lightbox-extensions#96]
## My Feedback
Yesterday I got a call from a client that videos weren't loading in the site's lightbox. Fortunately, after upgrading the video-addon plugin, everything worked fine. UNfortunately, it took several hours of troubleshooting, trial and error, deep dives into various web consoles and carefully refined google searches to get to that point.

When I went to the plugins page on this site, the SLB Video Addon was not among the plugins marked as in need of an update (In fact, the SLB plugin itself wasn't marked for update until I had upgraded WordPress itself). If it had been, it would have saved me a lot of grief.

I know the Video Addon is a premium plugin that doesn't participate in the WP plugin repository. But other premium plugins (e.g. Advanced Custom Fields Pro) don't have this issue... ACF Pro reported that an update was available, even though not as an auto-update.

I did not know an update was available until I stumbled onto an obscure console message, googled it two or three times until I found a support thread where you told another user they needed to upgrade. I hope you can find a way to remedy this.

Thank you for your attention and for your work.

Obbie King
La Crosse WI

**Comment by archetyped** [comment]
Hi, the distribution method being use for SLB extensions (Gumroad) unfortunately does support automatic updates/notifications in WordPress' admin.  However, an email notification is sent for every extension update, so updating your email settings to ensure you see those emails is recommended.

Also, plugins in WordPress' plugin directory (including SLB) mark what versions of WordPress a particular version of the plugin is compatible with.  Therefore, if you are using an outdated version of WordPress that later versions of a plugin does not support, you will not see an update notification in the site's admin until WordPress itself is updated to a compatible version.
