### ISSUE TITLE
[Video / Request]: Alert user when video is unavailable

### ISSUE THREAD

**Issue by purplearth** [archetyped/simple-lightbox-extensions#97]
## Description of feature/request

When a video is unavailable for whatever reason (blocked by publisher, no longer available, etc.), there should be an appropriate response for the user. As it is, the lightbox pinwheel spins with nothing loading. (In the background, the XHR request gets a response of "Forbidden"... At least that's what I see in Firefox's console.)

So the feature request: When the XHR request responds with something other than the desired content (403 error, "Forbidden" response, etc.), some sort of failure report is displayed to the user. An "extra" would be for an admin-defined image to display, where site developers could deliver their own "branded" failure message. Another "extra" would be to include a time-out condition as a failure.

Currently, when a request fails, the script dies with no report to the user.

## This feature would be used to...

...Improve the user experience.

Here's a link to a page under development that illustrates the problem...
https://filmmusicfoundation.org/xq/interviews/

(Long story, but client cannot get into the YouTube account hosting the videos to fix the problem on the YT end. Wants to keep the links in place in hopes this dilemma gets solved.)

**Comment by archetyped** [comment]
Thanks for the feedback.  This will likely be handled by [this planned enhancement to SLB](https://github.com/archetyped/simple-lightbox/issues/902), as handling non-accessible content is more of a core functionality.

This ticket has been referenced in the core ticket, so this ticket is being closed to keep all updates and discussion in the main ticket.

Thanks.
