### ISSUE TITLE
Not working on WordPress

### ISSUE THREAD

**Issue by Prachevs** [archetyped/simple-lightbox-extensions#98]
## Description of Problem

Good night,

I installed Simple Lightbox pligin on my WordPress but it is not working. It is active but when I click on images in the galleries nothing happens.

How do I solve this problem? The plugin and WordPress are updated in the latest version.

Thanks

Carlos Brandão

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please update your original post to fill in the requested details needed to evaluate your issue.

Thank you.

**Comment by Prachevs** [comment]
Hello sending update.

URL of Page exhibiting problem: site is running local with Xampp

Browser(s) exhibiting problem (Firefox, Chrome, etc.): Google Chorme

Version of SLB Installed: Simple Lightbox 2.8.1

Other plugins installed: Astra Widgets, Edito Classico, EWWW Image Optimizer, Microthemer, Post Types Order, Ultimate Addons For Gutenberg, WPForms Lite, Wps Hide Login

all updated

**Comment by archetyped** [comment]
Thank you for the additional details.

The first thing to check if nothing is happening when clicking on a gallery thumbnail is to ensure that the gallery is configured to include links to the full-size version of the images. Without links, there is nothing for visitors to click on and launch the lightbox.

See [WordPress' Gallery Documentation](https://wordpress.org/support/article/gallery-block/#link-to) for details on how to add configure linking.

If SLB still is not working once you have confirmed that the gallery thumbnails are linked, then [checking for theme/plugin conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) is the next recommended step.

Let me know what plugin/theme is preventing SLB from working on your site, and I would be glad to look into it further.  Please include name and link of conflicting plugin or theme.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
