### ISSUE TITLE
Simple Lightbox: WooCommerce Extension

### ISSUE THREAD

**Issue by SleepyCrom** [archetyped/simple-lightbox-extensions#99]
## Description of Problem

Not Working with WooCommerce Bundle Product plugin and WooCommerce Composite Products plugin.  

The short description on bundles and composite products works fine. But on "child" product in a bundle or composite product, it do not work.  

See https://www.travel4football.com/product/liverpool-v-brighton-vip-hospitality/
* First images work - short description on bundle product. But not short description on products that are bundle with main product. (See L15 link under THE ANFIELD BEAT LOUNGE - PREMIUM SEAT)

## Details

* URL of Page exhibiting problem:  https://www.travel4football.com/product/liverpool-v-brighton-vip-hospitality/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Tested on Mac: Firefox, Chrome and Safari.
* Version of SLB Installed: 2.8.1
* Other plugins installed (with versions): 
 - Wordpress 5.8.1 
 - WooCommerce 5.8.0
 - WooCommerce Product Bundles 6.10.1
 - WooCommerce Composite Products 8.3.3
 - Simple Lightbox 2.8.1 
 - Simple Lightbox: WooCommerce Extension 1.0.0-rc1

**Comment by archetyped** [comment]
Hi, please edit your original post to provide the details necessary to fully evaluate your issue.

Thank you.

**Comment by SleepyCrom** [comment]
Done.

**Comment by archetyped** [comment]
Thank you.  The WooCommerce extension is designed to support WooCommerce itself, but third-party extensions such as the Product Bundles and Composite Products extensions may not provide the necessary hooks to allow lightbox functionality to be added.

Access to these extensions have been requested for further investigation, but please note that as paid plugins, access to them cannot be guaranteed.

**Comment by archetyped** [comment]
WooCommerce have responded and will not provide any access or details on these extensions.  This unfortunately means that SLB's extension can only support the core WooCommerce plugin and extensions that use standard WooCommerce/WordPress filter hooks for their content unless this policy changes in the future.
